<template>
  <div>
    <div>
      <b-container>
        <div>
          <b-row>
            <b-col>
              <b-row>
                <div>
                  <b-button>Back</b-button>
                </div>
              </b-row>
              <b-row>
                <div>
                  <b-button>1</b-button>
                </div>
              </b-row>
              <b-row>
                <div>
                  <b-button>2</b-button>
                </div>
              </b-row>
              <b-row>
                <div>
                  <b-button>3</b-button>
                </div>
              </b-row>
              <b-row>
                <div>
                  <b-button>4</b-button>
                </div>
              </b-row>
              <b-row>
                <div>
                  <b-button>5</b-button>
                </div>
              </b-row>
              <b-row>
                <div>
                  <b-button>6</b-button>
                </div>
              </b-row>
              <b-row>
                <div>
                  <b-button>7</b-button>
                </div>
              </b-row>
            </b-col>
            <b-col>
              Layout
              <b-row>
                <b-button>A</b-button>
              </b-row>
              <b-row>
                <b-button>B</b-button>
              </b-row>
              <b-row>
                <b-button>C</b-button>
              </b-row>
              <b-row>
                <b-button>D</b-button>
              </b-row>
              <b-row>
                <b-button>E</b-button>
              </b-row>
            </b-col>
            <b-col>
              <div>
                SEQ100
              </div>
              <b-row>
                <b-col>
                  <div>
                    <img src="https://i.imgur.com/qx2zdy1.jpeg" style="width: 100%;">
                  </div>
                  <b-input></b-input>
                </b-col>
                <b-col>
                  <div>
                    <img src="https://i.imgur.com/qx2zdy1.jpeg" style="width: 100%;">
                  </div>
                  <b-input></b-input>
                </b-col>
              </b-row>
              <b-row>
                <b-col>
                  <b-button>1</b-button>
                  <b-button>1</b-button>
                  <b-button>1</b-button>
                  <b-button>1</b-button>
                  <b-button>1</b-button>
                  <b-button>1</b-button>
                </b-col>
              </b-row>
              <b-row>
                <b-col>
                  <b-button>1</b-button>
                  <b-button>1</b-button>
                  <b-button>1</b-button>
                  <b-button>1</b-button>
                  <b-button>1</b-button>
                  <b-button>1</b-button>
                </b-col>
              </b-row>
              <b-row>
                <b-col>
                  <b-button>1</b-button>
                  <b-button>2</b-button>
                  <b-button>3</b-button>
                  <b-button>4</b-button>
                  <b-button>5</b-button>
                  <b-button>6</b-button>
                </b-col>
              </b-row>
              <b-row>
                <b-button>
                  Confirm
                </b-button>
              </b-row>
            </b-col>
          </b-row>
        </div>
      </b-container>
    </div>
  </div>
</template>
<script>

</script>
<style lang="">
  
</style>